//! Native image-generation subsystem.
//!
//! Ports the frozen image surface of `packages/ai`:
//! - `images-models.ts` → [`provider`] and [`models`] (provider contract,
//!   parts builder, runtime collection with auth application)
//! - `images-api-registry.ts` → [`api_registry`] (api-keyed dispatch)
//! - `image-models.ts` + `image-models.generated.ts` → the built-in catalog
//!   below, loaded from `data/builtin-image-models.json` through
//!   `include_str!` only
//! - `images.ts` → [`generate_images`] (top-level dispatch)
//! - `api/openrouter-images.ts` + `providers/openrouter-images.ts` →
//!   [`openrouter`] (the only built-in adapter)
//!
//! Main integration note: this module is wired into the crate as
//! `pub mod images;` and re-exported by the crate owner after handoff.

mod api_registry;
mod models;
mod openrouter;
mod provider;
pub mod types;

pub use api_registry::{ImagesApiDispatch, get_images_api_provider, register_images_api_provider};
pub use models::{ImagesModels, ImagesModelsOptions, MutableImagesModels, create_images_models};
pub use openrouter::{OpenRouterImagesApi, openrouter_images_api, openrouter_images_provider};
pub use provider::{
    CreateImagesProviderOptions, ImagesProvider, ImagesRefreshFn, create_images_provider,
};
pub use types::{
    AssistantImages, ImagesApi, ImagesContext, ImagesInputContent, ImagesModel, ImagesOptions,
    ImagesOutput, ImagesOutputContent, ImagesStopReason, OPENROUTER_IMAGES_API, OnImagesPayloadFn,
    OnImagesResponseFn,
};

use std::collections::BTreeMap;
use std::sync::LazyLock;

use serde_json::Value;

use crate::catalog::CatalogError;

/// Logical path of the compiled-in image catalog payload.
pub const BUILTIN_IMAGE_MODELS_PATH: &str = "data/builtin-image-models.json";

/// Compiled-in built-in image catalog, generated by
/// `scripts/generate-image-models` from the frozen upstream catalog.
const BUILTIN_IMAGE_MODELS_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/data/builtin-image-models.json"
));

/// Provider → model-id → model metadata for the built-in image catalog.
pub type BuiltinImageModels = BTreeMap<String, BTreeMap<String, ImagesModel>>;

static BUILTIN_IMAGE_MODELS: LazyLock<Result<BuiltinImageModels, CatalogError>> =
    LazyLock::new(load_builtin_image_models);

/// Load the compiled-in built-in image catalog.
///
/// Parsed once and shared for the process lifetime; failures are typed and
/// path-rich, never panics.
///
/// # Errors
///
/// Returns a path-rich [`CatalogError`] when the compiled JSON is malformed
/// or a model fails required-field or catalog-key validation.
pub fn builtin_image_models() -> Result<&'static BuiltinImageModels, CatalogError> {
    BUILTIN_IMAGE_MODELS.as_ref().map_err(Clone::clone)
}

fn load_builtin_image_models() -> Result<BuiltinImageModels, CatalogError> {
    let root: Value = serde_json::from_str(BUILTIN_IMAGE_MODELS_JSON).map_err(|error| {
        CatalogError::parse(BUILTIN_IMAGE_MODELS_PATH, format!("invalid JSON: {error}"))
    })?;
    parse_builtin_image_models_value(&root, BUILTIN_IMAGE_MODELS_PATH)
}

fn parse_builtin_image_models_value(
    root: &Value,
    root_path: &str,
) -> Result<BuiltinImageModels, CatalogError> {
    let providers = root
        .as_object()
        .ok_or_else(|| CatalogError::validation(root_path, "catalog root must be a JSON object"))?;

    let mut out = BuiltinImageModels::new();
    for (provider_id, provider_value) in providers {
        let provider_path = format!("{root_path}.{provider_id}");
        let models_obj = provider_value.as_object().ok_or_else(|| {
            CatalogError::validation(
                provider_path.clone(),
                "provider entry must be a JSON object of models",
            )
        })?;

        let mut models = BTreeMap::new();
        for (model_id, model_value) in models_obj {
            let model_path = format!("{provider_path}.{model_id}");
            let model: ImagesModel =
                serde_json::from_value(model_value.clone()).map_err(|error| {
                    CatalogError::validation(
                        model_path.clone(),
                        format!("failed to decode image model: {error}"),
                    )
                })?;
            validate_image_model(&model, &model_path)?;
            if model.provider != *provider_id {
                return Err(CatalogError::validation(
                    format!("{model_path}.provider"),
                    format!(
                        "model.provider `{provider}` does not match catalog key `{provider_id}`",
                        provider = model.provider
                    ),
                ));
            }
            if model.id != *model_id {
                return Err(CatalogError::validation(
                    format!("{model_path}.id"),
                    format!(
                        "model.id `{id}` does not match catalog key `{model_id}`",
                        id = model.id
                    ),
                ));
            }
            models.insert(model_id.clone(), model);
        }
        out.insert(provider_id.clone(), models);
    }
    Ok(out)
}

/// Enforce the required non-empty image-model fields.
fn validate_image_model(model: &ImagesModel, path: &str) -> Result<(), CatalogError> {
    for (field, value) in [
        ("id", model.id.as_str()),
        ("name", model.name.as_str()),
        ("api", model.api.as_str()),
        ("provider", model.provider.as_str()),
        ("baseUrl", model.base_url.as_str()),
    ] {
        if value.trim().is_empty() {
            return Err(CatalogError::validation(
                format!("{path}.{field}"),
                "required field is empty",
            ));
        }
    }
    if model.input.is_empty() {
        return Err(CatalogError::validation(
            format!("{path}.input"),
            "required field must contain at least one modality",
        ));
    }
    if model.output.is_empty() {
        return Err(CatalogError::validation(
            format!("{path}.output"),
            "required field must contain at least one output modality",
        ));
    }
    Ok(())
}

/// Look up one built-in image model.
///
/// `None` on unknown provider/model ids, or while the compiled catalog is
/// invalid (the frozen import would have failed at startup instead).
#[must_use]
pub fn get_image_model(provider: &str, id: &str) -> Option<ImagesModel> {
    builtin_image_models().ok()?.get(provider)?.get(id).cloned()
}

/// Every built-in image provider id, in catalog order.
#[must_use]
pub fn get_image_providers() -> Vec<String> {
    builtin_image_models()
        .map(|models| models.keys().cloned().collect())
        .unwrap_or_default()
}

/// Every built-in image model for one provider, in catalog order.
#[must_use]
pub fn get_image_models(provider: &str) -> Vec<ImagesModel> {
    builtin_image_models()
        .ok()
        .and_then(|models| models.get(provider))
        .map(|models| models.values().cloned().collect())
        .unwrap_or_default()
}

/// Generate images through the dispatcher registered for `model.api`.
///
/// Mirrors the frozen `generateImages` entry point: the api registry resolves
/// the adapter, and an unregistered api fails with a provider error instead
/// of reaching any transport.
///
/// # Errors
///
/// Returns a [`ModelsError`] with the `provider` code when no dispatcher is
/// registered for `model.api`.
pub async fn generate_images(
    model: &ImagesModel,
    context: ImagesContext,
    options: ImagesOptions,
) -> Result<AssistantImages, crate::auth::error::ModelsError> {
    let Some(dispatch) = get_images_api_provider(&model.api) else {
        return Err(crate::auth::error::ModelsError::new(
            crate::auth::error::ModelsErrorCode::Provider,
            format!("No API provider registered for api: {}", model.api),
        ));
    };
    Ok(dispatch.generate_images(model, context, options).await)
}

#[cfg(test)]
#[expect(
    clippy::expect_used,
    reason = "unit tests use contextual failure messages"
)]
mod tests {
    use super::*;
    use crate::types::ModelInput;

    #[test]
    fn builtin_catalog_parses_with_matching_keys() {
        let models = builtin_image_models().expect("compiled catalog is valid");
        assert_eq!(get_image_providers(), vec!["openrouter".to_owned()]);

        let openrouter = models.get("openrouter").expect("openrouter models");
        assert!(!openrouter.is_empty(), "catalog carries openrouter models");
        for model in openrouter.values() {
            assert_eq!(model.api, OPENROUTER_IMAGES_API);
            assert_eq!(model.provider, "openrouter");
            assert_eq!(model.base_url, "https://openrouter.ai/api/v1");
        }
    }

    #[test]
    fn lookups_resolve_catalog_entries_and_misses() {
        let models = get_image_models("openrouter");
        let first = models.first().expect("catalog is non-empty");
        assert_eq!(
            get_image_model("openrouter", &first.id).expect("known id"),
            *first
        );
        assert!(get_image_model("openrouter", "not-a-model").is_none());
        assert!(get_image_model("unknown-provider", "x").is_none());
        assert!(get_image_models("unknown-provider").is_empty());
    }

    #[test]
    fn openrouter_provider_carries_static_catalog_models() {
        let provider = openrouter_images_provider();
        assert_eq!(provider.id(), "openrouter");
        assert_eq!(provider.name(), "OpenRouter");
        assert!(provider.refresh_models().is_none());
        let expected = get_image_models("openrouter").len();
        assert_eq!(
            provider.get_models().len(),
            expected,
            "static list mirrors the generated catalog"
        );
    }

    #[tokio::test]
    async fn generate_images_fails_for_unregistered_api() {
        let model = ImagesModel::new(
            "m",
            "M",
            "no-such-images-api",
            "openrouter",
            "https://image.example.test",
            vec![ModelInput::Text],
            vec![ImagesOutput::Image],
        );
        let error = generate_images(&model, ImagesContext::default(), ImagesOptions::default())
            .await
            .expect_err("unregistered api fails");
        assert_eq!(
            error.message(),
            "No API provider registered for api: no-such-images-api"
        );
    }

    #[tokio::test]
    async fn generate_images_dispatches_the_registered_builtin() {
        // No API key: the OpenRouter adapter reports the missing key through
        // the result frame instead of erroring the dispatch.
        let model = get_image_model("openrouter", "google/gemini-2.5-flash-image")
            .or_else(|| get_image_models("openrouter").into_iter().next())
            .expect("catalog carries at least one model");
        let result = generate_images(&model, ImagesContext::default(), ImagesOptions::default())
            .await
            .expect("dispatch resolves");
        assert_eq!(result.api, OPENROUTER_IMAGES_API);
        assert_eq!(result.provider, "openrouter");
        assert_eq!(result.model, model.id);
        assert_eq!(result.stop_reason, ImagesStopReason::Error);
        assert_eq!(
            result.error_message.as_deref(),
            Some("No API key for provider: openrouter")
        );
    }
}
