#!/usr/bin/env bun
/**
 * ARC11 witness generator (issue #168): the single owner of the shared
 * cross-language extension-bridge witness fixtures.
 *
 * Emits:
 *   - packages/pi-tui-protocol/tests/fixtures/frames.jsonl
 *     (provenance `#` header + one JSON frame per line)
 *   - packages/pi-tui-protocol/tests/fixtures/witness-manifest.json
 *     (generator, totalLines, sorted methodKindPairs, ordered
 *     lifecycleDiscriminants, modifierComboKeyEvents)
 *
 * Determinism: literal payload tables only; methodKindPairs sorted; the
 * manifest is rendered with `JSON.stringify(obj, null, "\t") + "\n"`; frames
 * are `\n`-joined with a trailing newline. No clock, environment, or network
 * input. `--check` regenerates in memory, byte-compares both committed
 * artifacts, prints the first differing line, and exits 1 on drift.
 *
 * Payload literals are grounded in their producers:
 *   - crates/pi-ext/src/protocol.rs (envelope, ErrorPayload, ToolUpdate,
 *     ProviderEvent, session/theme wire types)
 *   - crates/pi-ext/src/server.rs (RegistrySnapshot behind the
 *     extensions.load response, command.execute / tool.prepare /
 *     tool.validate / tool.renderHtml / message_update_delta handlers,
 *     callback_timeout_frame)
 *   - crates/pi-ext/src/adapters.rs (tool.prepare/validate/execute request
 *     literals, provider.stream payload assembly and stream_options_wire,
 *     methods::TOOL_CANCEL / PROVIDER_CANCEL)
 *   - crates/pi-ext/src/client.rs cancel_frame (tool.cancel /
 *     provider.cancel control events: id 0 event, payload {"id": <req id>})
 *
 * Lifecycle frames and manifest discriminants are derived from
 * `ALL_EVENT_TYPES` in crates/pi/src/core/extension_host.rs via
 * parseRustConstArray — never retyped here (plan Decision 3).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { parseRustConstArray } from "./xc-dispatch.ts";

const REPO_ROOT = resolve(import.meta.dirname, "../..");

const FRAMES_PATH = join(
	REPO_ROOT,
	"packages/pi-tui-protocol/tests/fixtures/frames.jsonl",
);
const MANIFEST_PATH = join(
	REPO_ROOT,
	"packages/pi-tui-protocol/tests/fixtures/witness-manifest.json",
);
const HOST_SOURCE_PATH = join(
	REPO_ROOT,
	"crates/pi/src/core/extension_host.rs",
);

/**
 * Provenance header written as the first line of frames.jsonl.
 * Every existing reader skips `#` lines; it is never counted in totalLines.
 */
export const PROVENANCE =
	"# GENERATED BY scripts/verification/gen-witness.ts — do not edit by hand";

/** Frame kind discriminant on the wire (`req` | `res` | `event` | `error`). */
export type WitnessFrameKind = "req" | "res" | "event" | "error";

/** One protocol frame; envelope key order is id, kind, method, payload. */
export interface FrameSpec {
	readonly id: number;
	readonly kind: WitnessFrameKind;
	readonly method: string;
	readonly payload: unknown;
}

// ---------------------------------------------------------------------------
// Layer 0 — the pre-ARC11 witness corpus (80 frames), embedded verbatim.
// The generator must reproduce these byte-for-byte; `--check` and the
// regeneration diff prove it.
// ---------------------------------------------------------------------------

export const BASE_SURFACES: readonly FrameSpec[] = [
	{ id: 1, kind: "req", method: "hello", payload: {"protocolVersion":1,"compatibilityVersion":"0.80.10"} },
	{ id: 1, kind: "res", method: "hello", payload: {"protocolVersion":1,"compatibilityVersion":"0.80.10"} },
	{ id: 0, kind: "event", method: "uiSlot", payload: {"key":"widget.demo","generation":3,"placement":"aboveEditor","height":2,"runs":[[{"text":"hi","style":{"bold":true,"fg":{"type":"named","name":"green"}}}],[{"text":"link","style":{"underline":true,"fg":{"type":"rgb","r":1,"g":2,"b":3},"link":{"id":"a","uri":"https://example.com"}}}]],"focusable":true,"cursor":{"col":1,"row":0},"overlayOptions":{"width":"50%","anchor":"top-center","margin":2,"nonCapturing":true}} },
	{ id: 0, kind: "event", method: "disposeSlot", payload: {"key":"widget.demo","generation":3} },
	{ id: 0, kind: "event", method: "extensionError", payload: {"code":"extension_error","message":"handler timed out","retryable":false,"data":{"path":"ext.ts"}} },
	{ id: 0, kind: "event", method: "toolUpdate", payload: {"toolCallId":"call_1","toolName":"bash","partialResult":{"text":"partial"}} },
	{ id: 0, kind: "event", method: "providerEvent", payload: {"providerId":"custom","callId":"p1","event":"chunk","data":{"delta":"x"}} },
	{ id: 7, kind: "req", method: "select", payload: {"title":"Pick","options":["a","b"],"timeoutMs":1000} },
	{ id: 7, kind: "res", method: "select", payload: {"value":"a"} },
	{ id: 8, kind: "req", method: "confirm", payload: {"title":"Sure?","message":"Really"} },
	{ id: 8, kind: "res", method: "confirm", payload: {"confirmed":true} },
	{ id: 9, kind: "req", method: "input", payload: {"title":"Name","placeholder":"you"} },
	{ id: 9, kind: "res", method: "input", payload: {"value":"Ada"} },
	{ id: 10, kind: "req", method: "editor", payload: {"title":"Edit","prefill":"draft"} },
	{ id: 10, kind: "res", method: "editor", payload: {"value":"final"} },
	{ id: 11, kind: "req", method: "notify", payload: {"message":"saved","type":"info"} },
	{ id: 11, kind: "res", method: "notify", payload: {"ok":true} },
	{ id: 12, kind: "req", method: "flags.set", payload: {"values":{"plan":true,"profile":"fast"}} },
	{ id: 12, kind: "res", method: "flags.set", payload: {"ok":true} },
	{ id: 13, kind: "req", method: "shortcut.execute", payload: {"key":"ctrl+alt+p"} },
	{ id: 13, kind: "res", method: "shortcut.execute", payload: {"handled":true} },
	{ id: 14, kind: "req", method: "uiEvent", payload: {"key":"widget.demo","generation":3,"event":{"type":"key","code":"enter","modifiers":{"ctrl":true},"kind":"press"},"data":"\r"} },
	{ id: 14, kind: "req", method: "uiEvent", payload: {"key":"widget.demo","generation":3,"event":{"type":"key","code":"a","modifiers":{"shift":true},"kind":"press"},"data":"A"} },
	{ id: 14, kind: "req", method: "uiEvent", payload: {"key":"widget.demo","generation":3,"event":{"type":"key","code":"b","modifiers":{"alt":true},"kind":"release"}} },
	{ id: 14, kind: "req", method: "uiEvent", payload: {"key":"widget.demo","generation":3,"event":{"type":"key","code":"c","modifiers":{"superKey":true},"kind":"repeat"}} },
	{ id: 14, kind: "req", method: "uiEvent", payload: {"key":"widget.demo","generation":3,"event":{"type":"key","code":"d","modifiers":{"ctrl":true,"shift":true},"kind":"release"},"data":""} },
	{ id: 14, kind: "req", method: "uiEvent", payload: {"key":"widget.demo","generation":3,"event":{"type":"paste","text":"a\nb"},"data":"a\nb"} },
	{ id: 14, kind: "req", method: "uiEvent", payload: {"key":"widget.demo","generation":3,"event":{"type":"focusGained"}} },
	{ id: 14, kind: "req", method: "uiEvent", payload: {"key":"widget.demo","generation":3,"event":{"type":"focusLost"}} },
	{ id: 14, kind: "req", method: "uiEvent", payload: {"key":"widget.demo","generation":3,"event":{"type":"resize","width":80,"height":24}} },
	{ id: 13, kind: "req", method: "terminalInput", payload: {"data":"x"} },
	{ id: 13, kind: "res", method: "terminalInput", payload: {"consume":true,"data":"y"} },
	{ id: 14, kind: "req", method: "measure", payload: {"key":"slot","width":80,"themeGeneration":1} },
	{ id: 14, kind: "res", method: "measure", payload: {"height":3} },
	{ id: 15, kind: "req", method: "render", payload: {"key":"slot","width":80,"themeGeneration":1} },
	{ id: 15, kind: "res", method: "render", payload: {"runs":[[{"text":"line1","style":{}}],[{"text":"line2","style":{"bold":true}}]]} },
	{ id: 15, kind: "error", method: "render", payload: {"code":"extension_error","message":"render failed","retryable":false} },
	{ id: 0, kind: "event", method: "theme.update", payload: {"theme":{"name":"dark","sourcePath":"/pkg/theme/dark.json","colorMode":"truecolor","fg":{"text":"#ededed","accent":39,"muted":""},"bg":{"selectedBg":"#0a0a0a"}},"terminalTheme":"light","themeMode":"auto","themeGeneration":42,"themes":[{"name":"mytheme","path":"/agent/themes/my-file.json","fileStem":"my-file","theme":{"name":"mytheme","colorMode":"256color","fg":{},"bg":{}}}]} },
	{ id: 0, kind: "event", method: "theme.set", payload: {"name":"light/dark","persist":true} },
	{ id: 0, kind: "event", method: "theme.set", payload: {"persist":false,"theme":{"colorMode":"truecolor","fg":{"text":"#ffffff"},"bg":{}}} },
	{ id: 0, kind: "event", method: "session.update", payload: {"sessionName":"My Session","thinkingLevel":"medium","activeTools":["read","bash"],"allTools":[{"name":"read","description":"Read a file","parameters":{"type":"object"},"source":"builtin"}],"commands":[{"name":"review","description":"Review changes","source":"extension"}],"model":{"id":"gpt-x","provider":"openai"},"scopedModels":[{"model":{"id":"gpt-x","provider":"openai"},"thinkingLevel":"high"},{"model":{"id":"haiku","provider":"anthropic"}}],"isIdle":true,"hasPendingMessages":false,"contextUsage":{"tokens":1200,"contextWindow":128000,"percent":0.9},"systemPrompt":"You are pi."} },
	{ id: 0, kind: "event", method: "session.command", payload: {"action":"setSessionName","name":"Renamed"} },
	{ id: 0, kind: "event", method: "session.command", payload: {"action":"sendMessage","message":{"customType":"note","content":"hi","display":true},"options":{"triggerTurn":false,"deliverAs":"nextTurn"}} },
	{ id: 0, kind: "event", method: "session.command", payload: {"action":"shutdown"} },
	{ id: 0, kind: "event", method: "session.command", payload: {"replacementToken":"tok-candidate","action":"setSessionName","name":"Candidate"} },
	{ id: 0, kind: "event", method: "session.command", payload: {"replacementToken":"tok-candidate","action":"sendMessage","message":{"customType":"note","content":"hi","display":true}} },
	{ id: 0, kind: "event", method: "session.command", payload: {"replacementToken":"tok-candidate","action":"shutdown"} },
	{ id: 17, kind: "req", method: "session.compact", payload: {"customInstructions":"keep decisions"} },
	{ id: 17, kind: "res", method: "session.compact", payload: {"result":{"summary":"…","firstKeptEntryId":"e9","tokensBefore":1200,"details":null}} },
	{ id: 16, kind: "req", method: "session.setModel", payload: {"model":{"id":"gpt-x","provider":"openai"}} },
	{ id: 16, kind: "res", method: "session.setModel", payload: {"success":true} },
	{ id: 0, kind: "event", method: "ui.control", payload: {"control":"setStatus","key":"lint","text":"3 warnings"} },
	{ id: 0, kind: "event", method: "ui.control", payload: {"control":"setEditorText","text":"draft"} },
	{ id: 0, kind: "event", method: "ui.control", payload: {"control":"setToolsExpanded","expanded":true} },
	{ id: 0, kind: "event", method: "ui.state", payload: {"editorText":"draft","toolsExpanded":true} },
	{ id: 18, kind: "req", method: "session.newSession", payload: {"parentSession":"parent-1"} },
	{ id: 18, kind: "res", method: "session.newSession", payload: {"cancelled":false,"replacementToken":"tok-1"} },
	{ id: 19, kind: "req", method: "session.fork", payload: {"entryId":"e1","position":"at"} },
	{ id: 19, kind: "res", method: "session.fork", payload: {"cancelled":false,"selectedText":"picked","replacementToken":"tok-2"} },
	{ id: 20, kind: "req", method: "session.navigateTree", payload: {"targetId":"e2"} },
	{ id: 20, kind: "res", method: "session.navigateTree", payload: {"cancelled":false} },
	{ id: 21, kind: "req", method: "session.navigateTree", payload: {"targetId":"e3","summarize":true,"customInstructions":"sum","replaceInstructions":true,"label":"L"} },
	{ id: 21, kind: "res", method: "session.navigateTree", payload: {"cancelled":false,"editorText":"draft","aborted":false,"summaryEntry":{"type":"branch_summary","id":"s1","parentId":"e3","timestamp":1,"fromId":"e0","summary":"kept"}} },
	{ id: 22, kind: "req", method: "session.switchSession", payload: {"sessionPath":"/tmp/s.jsonl"} },
	{ id: 22, kind: "res", method: "session.switchSession", payload: {"cancelled":true} },
	{ id: 23, kind: "req", method: "session.reload", payload: {} },
	{ id: 23, kind: "res", method: "session.reload", payload: {"replacementToken":"tok-3"} },
	{ id: 24, kind: "error", method: "session.newSession", payload: {"code":"replacement_busy","message":"session replacement in progress","retryable":true} },
	{ id: 25, kind: "error", method: "session.setModel", payload: {"code":"extension_error","message":"model not available","retryable":false} },
	{ id: 26, kind: "error", method: "session.compact", payload: {"code":"extension_error","message":"compaction failed","retryable":false} },
	{ id: 27, kind: "error", method: "session.fork", payload: {"code":"replacement_busy","message":"session replacement in progress","retryable":true} },
	{ id: 28, kind: "error", method: "session.navigateTree", payload: {"code":"extension_error","message":"entry not found","retryable":false} },
	{ id: 29, kind: "error", method: "session.switchSession", payload: {"code":"replacement_busy","message":"session replacement in progress","retryable":true} },
	{ id: 30, kind: "error", method: "session.reload", payload: {"code":"extension_error","message":"reload failed","retryable":false} },
	{ id: 31, kind: "req", method: "session.setupEntries", payload: {"replacementToken":"tok-1"} },
	{ id: 31, kind: "res", method: "session.setupEntries", payload: {"entries":[{"type":"message","id":"e1","parentId":null,"timestamp":"2025-01-01T00:00:00.000Z","message":{"role":"user","content":[{"type":"text","text":"hello"}]}}]} },
	{ id: 32, kind: "error", method: "session.setupEntries", payload: {"code":"extension_error","message":"stale replacement token","retryable":false} },
	{ id: 0, kind: "event", method: "session.replacementReady", payload: {"token":"tok-1"} },
	{ id: 0, kind: "event", method: "session.replacementAbort", payload: {"token":"tok-candidate"} },
	{ id: 0, kind: "event", method: "providers.update", payload: {"providers":[{"name":"custom","baseUrl":"https://custom.example/v1","api":"openai-completions","streamSimple":true,"models":[{"id":"custom-model","reasoning":false}]},{"name":"baseurl-only","baseUrl":"https://base.example/v1"}]} },
];

// ---------------------------------------------------------------------------
// Layer 1 — ARC11 gap surfaces (plan Decision 2). Payload literals mirror the
// producing handlers. Ids start at 40 (committed corpus max is 32); streaming
// updates reuse the parent request id; cancel control frames use id 0.
// ---------------------------------------------------------------------------

export const NEW_SURFACES: readonly FrameSpec[] = [
	// extensions.load (server.rs EXTENSIONS_LOAD_METHOD): request carries cwd +
	// projectTrusted; response is the full RegistrySnapshot — every struct
	// field present, in declaration order.
	{
		id: 44,
		kind: "req",
		method: "extensions.load",
		payload: { cwd: "/w", projectTrusted: true },
	},
	{
		id: 44,
		kind: "res",
		method: "extensions.load",
		payload: {
			tools: [
				{
					name: "bash",
					label: "Bash",
					description: "Run a shell command",
					parameters: { type: "object" },
					executionMode: "sequential",
				},
			],
			commands: [{ name: "x", description: "Run x", source: "/x.ts" }],
			shortcuts: [
				{ key: "ctrl+k", description: "Trigger x", extensionPath: "/x.ts" },
			],
			flags: [
				{
					name: "verbose",
					description: "Verbose logging",
					type: "boolean",
					extensionPath: "/x.ts",
					default: false,
				},
			],
			renderers: [{ type: "tool", name: "bash" }],
			providers: [
				{
					name: "custom",
					streamSimple: true,
					baseUrl: "https://custom.example/v1",
					api: "openai-completions",
				},
			],
			handlers: ["input", "message_update"],
			terminalInput: true,
			extensions: 1,
			errors: [{ path: "/missing.ts", error: "module not found" }],
		},
	},
	// command.execute (server.rs COMMAND_EXECUTE_METHOD): handler answers
	// {"ok": true}.
	{ id: 45, kind: "req", method: "command.execute", payload: { command: "/x", args: "a" } },
	{ id: 45, kind: "res", method: "command.execute", payload: { ok: true } },
	// tool.prepare (adapters.rs methods::TOOL_PREPARE): request is
	// {"name", "args"}; the host echoes prepared args under "args".
	{ id: 46, kind: "req", method: "tool.prepare", payload: { name: "bash", args: { cmd: "ls" } } },
	{ id: 46, kind: "res", method: "tool.prepare", payload: { args: { cmd: "ls" } } },
	// tool.validate (adapters.rs methods::TOOL_VALIDATE): same shape as prepare.
	{ id: 47, kind: "req", method: "tool.validate", payload: { name: "bash", args: { cmd: "ls" } } },
	{ id: 47, kind: "res", method: "tool.validate", payload: { args: { cmd: "ls" } } },
	// tool.execute (adapters.rs methods::TOOL_EXECUTE): request literal from
	// adapters.rs {name, toolCallId, args, prepared}; correlated toolUpdate
	// events carry the parent request id and an AgentToolResult-shaped
	// partialResult (content + details); the terminal res is the tool result.
	{
		id: 40,
		kind: "req",
		method: "tool.execute",
		payload: { name: "bash", toolCallId: "call_2", args: { cmd: "ls" }, prepared: true },
	},
	{
		id: 40,
		kind: "event",
		method: "toolUpdate",
		payload: {
			toolCallId: "call_2",
			toolName: "bash",
			partialResult: { content: [{ type: "text", text: "partial" }], details: {} },
		},
	},
	{
		id: 40,
		kind: "event",
		method: "toolUpdate",
		payload: {
			toolCallId: "call_2",
			toolName: "bash",
			partialResult: { content: [{ type: "text", text: "partial" }], details: { stage: "half" } },
		},
	},
	{
		id: 40,
		kind: "res",
		method: "tool.execute",
		payload: { content: [{ type: "text", text: "done" }], details: {} },
	},
	// Error variant: correlated error frame with the ErrorPayload shape.
	{
		id: 41,
		kind: "req",
		method: "tool.execute",
		payload: { name: "bash", toolCallId: "call_3", args: { cmd: "fail" }, prepared: true },
	},
	{
		id: 41,
		kind: "error",
		method: "tool.execute",
		payload: { code: "extension_error", message: "tool failed", retryable: false },
	},
	// tool.cancel control frame — exact cancel_frame shape (client.rs): an
	// id-0 event whose payload names the cancelled request id.
	{ id: 0, kind: "event", method: "tool.cancel", payload: { id: 40 } },
	// provider.stream (adapters.rs methods::PROVIDER_STREAM): request payload
	// is {providerId, model, context, options}; options keys come from
	// stream_options_wire; correlated providerEvent frames precede the
	// terminal response (the default endpoint answers {}).
	{
		id: 42,
		kind: "req",
		method: "provider.stream",
		payload: {
			providerId: "custom",
			model: { id: "custom-model", provider: "custom" },
			context: {},
			options: { temperature: 0.2, maxTokens: 128, apiKey: "sk-test", sessionId: "s1", maxRetries: 2 },
		},
	},
	{
		id: 42,
		kind: "event",
		method: "providerEvent",
		payload: { providerId: "custom", callId: "p1", event: "chunk", data: { type: "text_delta", delta: "hel" } },
	},
	{
		id: 42,
		kind: "event",
		method: "providerEvent",
		payload: { providerId: "custom", callId: "p1", event: "chunk", data: { type: "text_delta", delta: "lo" } },
	},
	{ id: 42, kind: "res", method: "provider.stream", payload: {} },
	{
		id: 43,
		kind: "req",
		method: "provider.stream",
		payload: {
			providerId: "custom",
			model: { id: "custom-model", provider: "custom" },
			context: {},
			options: { temperature: 0.2 },
		},
	},
	{
		id: 43,
		kind: "error",
		method: "provider.stream",
		payload: { code: "extension_error", message: "provider stream failed", retryable: false },
	},
	// provider.cancel control frame (client.rs cancel_frame).
	{ id: 0, kind: "event", method: "provider.cancel", payload: { id: 42 } },
	// tool.renderHtml (server.rs TOOL_RENDER_HTML_METHOD): request is
	// {phase, toolName, payload}; the host answers the renderer's open value
	// ({"html": ...}); endpoints without a renderer answer {}.
	{
		id: 48,
		kind: "req",
		method: "tool.renderHtml",
		payload: { phase: "call", toolName: "bash", payload: { cmd: "ls" } },
	},
	{ id: 48, kind: "res", method: "tool.renderHtml", payload: { html: "<b>ok</b>" } },
	{
		id: 49,
		kind: "req",
		method: "tool.renderHtml",
		payload: { phase: "result", toolName: "bash", payload: { content: [{ type: "text", text: "done" }], details: {} } },
	},
	{ id: 49, kind: "res", method: "tool.renderHtml", payload: { html: "<b>done</b>" } },
	// message_update_delta (server.rs MESSAGE_UPDATE_DELTA_METHOD): the
	// compact delta request maps onto the advertised message_update handler;
	// the default hook answer is {} (server.rs NativeExtension docs).
	{
		id: 50,
		kind: "req",
		method: "message_update_delta",
		payload: { type: "message_update_delta", event: { type: "text_delta", delta: "hi" } },
	},
	{ id: 50, kind: "res", method: "message_update_delta", payload: {} },
];

// ---------------------------------------------------------------------------
// Layer 2 — lifecycle frames, derived from ALL_EVENT_TYPES (never retyped).
// ---------------------------------------------------------------------------

/** Representative lifecycle discriminants that also witness correlated res
 * frames. The default hook answer is `{}`. */
const LIFECYCLE_RES_REPS: readonly string[] = [
	"project_trust",
	"message_end",
	"tool_call",
];

/** Discriminant witnessing the callback-deadline error frame
 * (callback_timeout_frame: code "timeout", not retryable). */
const LIFECYCLE_ERROR_REP = "message_update";

/** First id of the 35 lifecycle req frames (after the last gap-surface id). */
const FIRST_LIFECYCLE_ID = 51;

function lifecycleFrames(lifecycle: readonly string[]): readonly FrameSpec[] {
	const frames: FrameSpec[] = [];
	lifecycle.forEach((name, index) => {
		frames.push({
			id: FIRST_LIFECYCLE_ID + index,
			kind: "req",
			method: name,
			payload: { type: name },
		});
	});
	for (const rep of LIFECYCLE_RES_REPS) {
		const index = lifecycle.indexOf(rep);
		if (index < 0) {
			throw new Error(`lifecycle res representative missing from ALL_EVENT_TYPES: ${rep}`);
		}
		frames.push({ id: FIRST_LIFECYCLE_ID + index, kind: "res", method: rep, payload: {} });
	}
	const errorIndex = lifecycle.indexOf(LIFECYCLE_ERROR_REP);
	if (errorIndex < 0) {
		throw new Error(`lifecycle error representative missing from ALL_EVENT_TYPES: ${LIFECYCLE_ERROR_REP}`);
	}
	frames.push({
		id: FIRST_LIFECYCLE_ID + errorIndex,
		kind: "error",
		method: LIFECYCLE_ERROR_REP,
		payload: {
			code: "timeout",
			message: "extension callback exceeded its server-side deadline",
			retryable: false,
		},
	});
	return frames;
}

/** Every witnessed frame, in canonical order: base corpus, gap surfaces,
 * lifecycle reqs in ALL_EVENT_TYPES order, lifecycle res reps, lifecycle error. */
export function allFrames(lifecycle: readonly string[]): readonly FrameSpec[] {
	return [...BASE_SURFACES, ...NEW_SURFACES, ...lifecycleFrames(lifecycle)];
}

/** Serialize the frames.jsonl artifact (provenance header + JSONL frames). */
export function buildFrames(lifecycle: readonly string[]): string {
	const lines = allFrames(lifecycle).map((frame) => JSON.stringify(frame));
	return `${PROVENANCE}\n${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------

/** One modifier-combination key event extracted from the uiEvent frames. */
export interface KeyComboEvent {
	readonly code: string;
	readonly modifiers: unknown;
	readonly kind: string;
}

/** witness-manifest.json schema (plan Decision 3). */
export interface WitnessManifest {
	readonly generator: string;
	readonly totalLines: number;
	readonly methodKindPairs: readonly (readonly [string, string])[];
	readonly lifecycleDiscriminants: readonly string[];
	/** Witnessed modifier-combo key events in fixture order. */
	readonly modifierComboKeyEvents: readonly KeyComboEvent[];
	/** sha256 hex of the fixture text; pins payload bytes, not just envelopes. */
	readonly fixtureSha256: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function collectKeyCombo(payload: unknown, out: KeyComboEvent[]): void {
	if (!isRecord(payload)) return;
	const event = payload["event"];
	if (!isRecord(event) || event["type"] !== "key") return;
	const modifiers = event["modifiers"];
	out.push({
		code: String(event["code"]),
		modifiers: isRecord(modifiers) ? modifiers : {},
		kind: String(event["kind"]),
	});
}

/** Serialize the witness-manifest.json artifact (tab-indented JSON + newline). */
export function buildManifest(
	lifecycle: readonly string[],
): { manifest: WitnessManifest; text: string } {
	const frames = allFrames(lifecycle);
	const pairKeys = new Set<string>();
	const modifierComboKeyEvents: KeyComboEvent[] = [];
	for (const frame of frames) {
		pairKeys.add(`${frame.method}\u0000${frame.kind}`);
		if (frame.method === "uiEvent" && frame.kind === "req") {
			collectKeyCombo(frame.payload, modifierComboKeyEvents);
		}
	}
	const methodKindPairs = [...pairKeys].sort().map((key) => {
		const separator = key.indexOf("\u0000");
		return [key.slice(0, separator), key.slice(separator + 1)] as const;
	});
	const manifest: WitnessManifest = {
		generator: "scripts/verification/gen-witness.ts",
		totalLines: frames.length,
		methodKindPairs,
		lifecycleDiscriminants: [...lifecycle],
		modifierComboKeyEvents,
		fixtureSha256: new Bun.CryptoHasher("sha256")
			.update(buildFrames(lifecycle))
			.digest("hex"),
	};
	return { manifest, text: `${JSON.stringify(manifest, null, "\t")}\n` };
}

// ---------------------------------------------------------------------------
// Inputs and drift check
// ---------------------------------------------------------------------------

/** Parse ALL_EVENT_TYPES from the extension-host Rust source; fails closed. */
export function loadLifecycle(hostSource: string): readonly string[] {
	const lifecycle = parseRustConstArray(hostSource, "ALL_EVENT_TYPES");
	if (lifecycle === null) {
		throw new Error(
			"ALL_EVENT_TYPES array not found in crates/pi/src/core/extension_host.rs",
		);
	}
	return lifecycle;
}

/**
 * Byte-compare one committed artifact against its generated form.
 * Returns [] when identical, else one violation naming the first
 * differing line (or the length mismatch).
 */
export function diffArtifact(
	label: string,
	committed: string,
	generated: string,
): string[] {
	if (committed === generated) return [];
	const committedLines = committed.split("\n");
	const generatedLines = generated.split("\n");
	const count = Math.min(committedLines.length, generatedLines.length);
	for (let i = 0; i < count; i++) {
		const a = committedLines[i] ?? "";
		const b = generatedLines[i] ?? "";
		if (a !== b) {
			return [
				`${label}: first differing line ${i + 1}\n  committed: ${a}\n  generated: ${b}`,
			];
		}
	}
	return [
		`${label}: length mismatch — committed ${committedLines.length} lines, generated ${generatedLines.length} lines`,
	];
}

function main(): void {
	const check = process.argv.includes("--check");
	const lifecycle = loadLifecycle(readFileSync(HOST_SOURCE_PATH, "utf8"));
	const framesText = buildFrames(lifecycle);
	const { text: manifestText } = buildManifest(lifecycle);
	if (check) {
		const violations = [
			...diffArtifact("frames.jsonl", readFileSync(FRAMES_PATH, "utf8"), framesText),
			...diffArtifact("witness-manifest.json", readFileSync(MANIFEST_PATH, "utf8"), manifestText),
		];
		if (violations.length > 0) {
			for (const violation of violations) {
				process.stderr.write(`${violation}\n`);
			}
			process.exit(1);
		}
		process.stdout.write("WITNESS_OK\n");
		return;
	}
	writeFileSync(FRAMES_PATH, framesText);
	writeFileSync(MANIFEST_PATH, manifestText);
	process.stdout.write(`WITNESS_OK ${FRAMES_PATH} ${MANIFEST_PATH}\n`);
}

if (import.meta.main) main();
